version: "3.9"

services:
  builder: 
    build: .
    volumes:
    - ./app:/app
    ports:
    - 80:80
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    # env_file:
    # - conf/.env
    depends_on: 
    - mysql

  mysql:
    image: mysql:8.0.19
    ports:
     - 3306:3306
    # volumes:
    # - ./dbfiles:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=py_device
      - MYSQL_ROOT_PASSWORD=password
    # command: mysqld --init-file=
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    restart: always
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536    
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    user: root
    volumes:
      - ./conf/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro


volumes:
 esdata: