- FW_INT1_yaml:
    id: 1
    manufacturer_id: 1
    mgmt_interface_id: 1
    model: VM100
    state: !Device_State 'unknown'
- BranchCSR1000v_yaml:
    id: 2
    manufacturer_id: 2
    mgmt_interface_id: 3
    model: VM100
    state: !Device_State 'unknown'
- FW_INT2_yaml:
    id: 3
    manufacturer_id: 1
    mgmt_interface_id: 5
    model: VM100
    state: !Device_State 'unknown'
- FW_INT3_ini:
    id: 5
    manufacturer_id: 1
    mgmt_interface_id: 7
    model: VM100
    state: !Device_State 'unknown'
