import os

INVENTORY_SOURCE = os.getenv("INVENTORY_SOURCE")
MANUFACTURERS_SOURCE = os.getenv("MANUFACTURERS_SOURCE")
INTERFACES_SOURCE = os.getenv("INTERFACES_SOURCE")

INVENTORY_FILE_SOURCE = os.getenv("INVENTORY_FILE_SOURCE")
MANUFACTURERS_FILE_SOURCE = os.getenv("MANUFACTURERS_FILE_SOURCE")
INTERFACES_FILE_SOURCE = os.getenv("INTERFACES_FILE_SOURCE")
